// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice =
  | FooterSectionSlice
  | CarrouselSlice
  | NavBarSlice
  | AlternateGridSlice
  | ContentSectionSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Item in *AlternateGrid → Default → Primary → items*
 */
export interface AlternateGridSliceDefaultPrimaryItemsItem {
  /**
   * title field in *AlternateGrid → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *AlternateGrid → Image Right → Primary → items*
 */
export interface AlternateGridSliceImageRightPrimaryItemsItem {
  /**
   * title field in *AlternateGrid → Image Right → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Image Right → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *AlternateGrid → Default → Primary*
 */
export interface AlternateGridSliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: alternate_grid.default.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * items field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<AlternateGridSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for AlternateGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AlternateGridSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *AlternateGrid → Image Right → Primary*
 */
export interface AlternateGridSliceImageRightPrimary {
  /**
   * eyebrowHeadline field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: alternate_grid.imageRight.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * items field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<AlternateGridSliceImageRightPrimaryItemsItem>
  >;
}

/**
 * Image Right variation for AlternateGrid Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<AlternateGridSliceImageRightPrimary>,
  never
>;

/**
 * Slice variation for *AlternateGrid*
 */
type AlternateGridSliceVariation =
  | AlternateGridSliceDefault
  | AlternateGridSliceImageRight;

/**
 * AlternateGrid Shared Slice
 *
 * - **API ID**: `alternate_grid`
 * - **Description**: AlternateGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSlice = prismic.SharedSlice<
  "alternate_grid",
  AlternateGridSliceVariation
>;

/**
 * Item in *Carrousel → Default → Primary → carrousel_cards*
 */
export interface CarrouselSliceDefaultPrimaryCarrouselCardsItem {
  /**
   * card_icon field in *Carrousel → Default → Primary → carrousel_cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel.default.primary.carrousel_cards[].card_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_icon: prismic.ImageField<never>;

  /**
   * card_title field in *Carrousel → Default → Primary → carrousel_cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel.default.primary.carrousel_cards[].card_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_title: prismic.KeyTextField;

  /**
   * card_description field in *Carrousel → Default → Primary → carrousel_cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel.default.primary.carrousel_cards[].card_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_description: prismic.KeyTextField;

  /**
   * card_link field in *Carrousel → Default → Primary → carrousel_cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel.default.primary.carrousel_cards[].card_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card_link: prismic.LinkField;
}

/**
 * Primary content in *Carrousel → Default → Primary*
 */
export interface CarrouselSliceDefaultPrimary {
  /**
   * carrousel_title field in *Carrousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel.default.primary.carrousel_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carrousel_title: prismic.KeyTextField;

  /**
   * carrousel_information field in *Carrousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel.default.primary.carrousel_information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carrousel_information: prismic.KeyTextField;

  /**
   * carrousel_cards field in *Carrousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carrousel.default.primary.carrousel_cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carrousel_cards: prismic.GroupField<
    Simplify<CarrouselSliceDefaultPrimaryCarrouselCardsItem>
  >;
}

/**
 * Default variation for Carrousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarrouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarrouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Carrousel*
 */
type CarrouselSliceVariation = CarrouselSliceDefault;

/**
 * Carrousel Shared Slice
 *
 * - **API ID**: `carrousel`
 * - **Description**: Carrousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarrouselSlice = prismic.SharedSlice<
  "carrousel",
  CarrouselSliceVariation
>;

/**
 * Primary content in *ContentSection → Default → Primary*
 */
export interface ContentSectionSliceDefaultPrimary {
  /**
   * title field in *ContentSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *ContentSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * phone_image field in *ContentSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_section.default.primary.phone_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  phone_image: prismic.ImageField<never>;

  /**
   * text field in *ContentSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_section.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * downloadLink field in *ContentSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_section.default.primary.download_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  download_link: prismic.LinkField;

  /**
   * more_information_link field in *ContentSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_section.default.primary.more_information_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  more_information_link: prismic.LinkField;
}

/**
 * Default variation for ContentSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentSection*
 */
type ContentSectionSliceVariation = ContentSectionSliceDefault;

/**
 * ContentSection Shared Slice
 *
 * - **API ID**: `content_section`
 * - **Description**: ContentSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSectionSlice = prismic.SharedSlice<
  "content_section",
  ContentSectionSliceVariation
>;

/**
 * Primary content in *FooterSection → Default → Primary*
 */
export interface FooterSectionSliceDefaultPrimary {
  /**
   * footer_section_image field in *FooterSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.default.primary.footer_section_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footer_section_image: prismic.ImageField<never>;

  /**
   * footer_section_main_text field in *FooterSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.default.primary.footer_section_main_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_section_main_text: prismic.RichTextField;

  /**
   * footer_section_secondary_text field in *FooterSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.default.primary.footer_section_secondary_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_section_secondary_text: prismic.RichTextField;

  /**
   * footer_section_link field in *FooterSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.default.primary.footer_section_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  footer_section_link: prismic.LinkField;

  /**
   * footer_section_background_color field in *FooterSection → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.default.primary.footer_section_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  footer_section_background_color: prismic.ColorField;

  /**
   * footer_section_highlighted_text field in *FooterSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.default.primary.footer_section_highlighted_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_section_highlighted_text: prismic.KeyTextField;
}

/**
 * Default variation for FooterSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FooterSection*
 */
type FooterSectionSliceVariation = FooterSectionSliceDefault;

/**
 * FooterSection Shared Slice
 *
 * - **API ID**: `footer_section`
 * - **Description**: FooterSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSectionSlice = prismic.SharedSlice<
  "footer_section",
  FooterSectionSliceVariation
>;

/**
 * Item in *NavBar → Default → Primary → links*
 */
export interface NavBarSliceDefaultPrimaryLinksItem {
  /**
   * link field in *NavBar → Default → Primary → links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_bar.default.primary.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *NavBar → Default → Primary*
 */
export interface NavBarSliceDefaultPrimary {
  /**
   * logo field in *NavBar → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_bar.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * links field in *NavBar → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_bar.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavBarSliceDefaultPrimaryLinksItem>>;

  /**
   * sign_in field in *NavBar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_bar.default.primary.sign_in
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sign_in: prismic.LinkField;

  /**
   * sign_up field in *NavBar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_bar.default.primary.sign_up
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sign_up: prismic.LinkField;
}

/**
 * Default variation for NavBar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavBarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavBarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavBar*
 */
type NavBarSliceVariation = NavBarSliceDefault;

/**
 * NavBar Shared Slice
 *
 * - **API ID**: `nav_bar`
 * - **Description**: NavBar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavBarSlice = prismic.SharedSlice<"nav_bar", NavBarSliceVariation>;

/**
 * Default variation for Prueba Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PruebaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Prueba*
 */
type PruebaSliceVariation = PruebaSliceDefault;

/**
 * Prueba Shared Slice
 *
 * - **API ID**: `prueba`
 * - **Description**: Prueba
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PruebaSlice = prismic.SharedSlice<"prueba", PruebaSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      AlternateGridSlice,
      AlternateGridSliceDefaultPrimaryItemsItem,
      AlternateGridSliceDefaultPrimary,
      AlternateGridSliceImageRightPrimaryItemsItem,
      AlternateGridSliceImageRightPrimary,
      AlternateGridSliceVariation,
      AlternateGridSliceDefault,
      AlternateGridSliceImageRight,
      CarrouselSlice,
      CarrouselSliceDefaultPrimaryCarrouselCardsItem,
      CarrouselSliceDefaultPrimary,
      CarrouselSliceVariation,
      CarrouselSliceDefault,
      ContentSectionSlice,
      ContentSectionSliceDefaultPrimary,
      ContentSectionSliceVariation,
      ContentSectionSliceDefault,
      FooterSectionSlice,
      FooterSectionSliceDefaultPrimary,
      FooterSectionSliceVariation,
      FooterSectionSliceDefault,
      NavBarSlice,
      NavBarSliceDefaultPrimaryLinksItem,
      NavBarSliceDefaultPrimary,
      NavBarSliceVariation,
      NavBarSliceDefault,
      PruebaSlice,
      PruebaSliceVariation,
      PruebaSliceDefault,
    };
  }
}
